SELECT  'YOUNGEST' AS TYPE, NAME, BIRTHDAY FROM worker WHERE BIRTHDAY = (SELECT max(BIRTHDAY) FROM worker)
UNION
SELECT  'ELDEST' AS TYPE, NAME, BIRTHDAY from worker WHERE BIRTHDAY = (SELECT min(BIRTHDAY) FROM worker)
